version: "3.7"

services:
  database:
    image: postgres
    container_name: database_twitteer
    restart: always
    ports:
      - 3333:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=BlueBirdAndRockets
      - POSTGRES_DB=twitteer
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: twitteer
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    links:
      - database
    depends_on:
      - database
  
volumes:
  pgdata:
